
spring.application.name=hipodromo

# Puerto dinámico para Railway (localmente usa 8080 como fallback)
server.port=${PORT:8080}

# Credenciales de Supabase (se pueden sobreescribir con variables de entorno en Railway)
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres.mtkkbniyzkixpnyauham}
spring.datasource.password=${DB_PASSWORD:7vV?%b$W4ExZ$B$}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Deshabilitar open-in-view para evitar advertencia de Hibernate
spring.jpa.open-in-view=false